services:
  reacher:
    image: reacherhq/backend:latest
    container_name: reacher_local
    restart: always
    ports:
      - "8080:8080"
    environment:
      REACHER_SMTP_PROXY_HOST: ${MAIL_FLEET_PROXY_HOST}
      REACHER_SMTP_PROXY_PORT: ${MAIL_FLEET_PROXY_PORT}
      REACHER_SMTP_PROXY_USERNAME: ${MAIL_FLEET_PROXY_USERNAME}
      REACHER_SMTP_PROXY_PASSWORD: ${MAIL_FLEET_PROXY_PASSWORD}